// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVXqNI2zA56zUWXDupGDai0Nlvd02Grwg',
    appId: '1:625679218153:web:e4098ffe1a77d3c4010778',
    messagingSenderId: '625679218153',
    projectId: 'diaryapp-476b1',
    authDomain: 'diaryapp-476b1.firebaseapp.com',
    storageBucket: 'diaryapp-476b1.appspot.com',
    measurementId: 'G-XFKBMV6YTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7HqtYBQ8fVYQek2qicLHeK7WAMX9S9RE',
    appId: '1:625679218153:android:2ce8523ef24c52e6010778',
    messagingSenderId: '625679218153',
    projectId: 'diaryapp-476b1',
    storageBucket: 'diaryapp-476b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGaN0AM_d94SwL87KOs5R_lGOfROG7i4c',
    appId: '1:625679218153:ios:ad3e96fd7b8812b4010778',
    messagingSenderId: '625679218153',
    projectId: 'diaryapp-476b1',
    storageBucket: 'diaryapp-476b1.appspot.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGaN0AM_d94SwL87KOs5R_lGOfROG7i4c',
    appId: '1:625679218153:ios:ad3e96fd7b8812b4010778',
    messagingSenderId: '625679218153',
    projectId: 'diaryapp-476b1',
    storageBucket: 'diaryapp-476b1.appspot.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVXqNI2zA56zUWXDupGDai0Nlvd02Grwg',
    appId: '1:625679218153:web:0d2775ae964e3ff5010778',
    messagingSenderId: '625679218153',
    projectId: 'diaryapp-476b1',
    authDomain: 'diaryapp-476b1.firebaseapp.com',
    storageBucket: 'diaryapp-476b1.appspot.com',
    measurementId: 'G-XGKG0FKZKK',
  );
}
